version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-servidores-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - api-servidores-network
    depends_on:
      - db
      - minio

  pgadmin:
  image: dpage/pgadmin4
  container_name: pgadmin
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@example.com
    PGADMIN_DEFAULT_PASSWORD: admin
  ports:
    - "5050:80"
  depends_on:
    - db
  networks:
    - api-servidores-network
  db:
    image: postgres:14
    container_name: api-servidores-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: api_servidores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-servidores-network

  minio:
    image: minio/minio
    container_name: api-servidores-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - api-servidores-network

networks:
  api-servidores-network:
    driver: bridge

volumes:
  pgdata:
  minio_data:
